---
- name: Fetch existing {{ container }} download clients
  uri:
    url: "https://{{ sonarr_domain }}/api/v3/downloadclient"
    method: GET
    headers:
      X-Api-Key: "{{ sonarr_api_key }}"
  register: download_clients_resp

- name: Get existing {{ container }} download client names
  set_fact:
    download_clients_existing: "{{ download_clients_resp.json | selectattr('name', 'defined') | map(attribute='name') }}"

- name: Add download clients to {{ container }}
  uri:
    url: "https://{{ sonarr_domain }}/api/v3/downloadclient"
    method: POST
    body_format: json
    status_code: [200, 201]
    headers:
      X-Api-Key: "{{ sonarr_api_key }}"
    body: "{{ item | combine(download_client_defaults) | combine({ 'fields': item.fields | dict2items(key_name='name', value_name='value') }) }}"
  loop: "{{ download_clients }}"
  when: not (item.name in download_clients_existing)