- name: Create / Run {{ container }} container
  docker_container:
    name: "{{ container }}"
    image: lscr.io/linuxserver/sonarr:latest
    networks:
      - name: "swag_{{ network }}_bridge"
    pull: true
    state: started
    env:
      PUID: "{{ target_username_puid }}"
      PGID: "{{ target_username_pgid }}"
      TZ: "{{ timezone }}"
    ports:
      - 8989:8989
    volumes:
      - "{{ docker_dir }}/{{ container }}:/config"
      - "{{ mergerfs_root }}/downloads:/downloads"
      - "{{ mergerfs_root }}/media/tv:/tv"
    restart_policy: unless-stopped

- name: Set target_container to {{ container }}
  set_fact:
    target_container: "{{ container }}"

- include_tasks: get_single_docker_container_ready.yml