constants:
  pg_user: "${PG_USER}"
  pg_password: "${PG_PASS}"
  maria_user: "${MARIA_USER}"
  maria_password: "${MARIA_PASS}"
  

source_directories: []

repositories:
  - path: /mnt/backup/db
    label: local

archive_name_format: 'db-backup-{now:%Y-%m-%d-%H%M%S}'

read_special: true

sqlite_databases:
  # gw
  - name: pgadmin
    path: /mnt/source/docker/pgadmin/pgadmin4.db
    restore_path: /mnt/restore/pgadmin/pgadmin4.db
  - name: nginx-proxy-manager
    path: /mnt/source/docker/nginx-proxy-manager/data/database.sqlite
    restore_path: /mnt/restore/nginx-proxy-manager/data/database.sqlite

postgresql_databases:
  - name: all
    hostname: postgres
    port: 5432
    username: "{pg_user}"
    password: "{pg_password}"
    no_owner: true
    # custom?
    format: directory
    #ssl_mode: disable

mariadb_databases:
  - name: all
    hostname: host.docker.internal
    username: "{maria_user}"
    password: "{maria_password}"
    format: sql

after_backup:
  - echo Syncing backups
  - rclone sync /mnt/backup/db bb:phoenix0/db --progress --stats-one-line --stats 1s
  - rclone sync /mnt/backup/db koofr:/db --progress --stats-one-line --stats 1s
  - rclone sync /mnt/backup/db gdrive:/db --progress --stats-one-line --stats 1s
  - echo Finished backup sync

<<: !include /etc/borgmatic.d/shared/shared-config.yaml