source_directories:
  - /mnt/source/docker/

patterns:
  - R /
  # ignore all sqlite dbs
  - '- **/*.db*'
  - '- **/*.sqlite*'
  # dockge
  - '+ /mnt/source/docker/dockge/stacks/**'
  # gw
  - '+ /mnt/source/docker/lldap/**'
  - '- /mnt/source/docker/nginx-proxy-manager/data/logs'
  - '+ /mnt/source/docker/nginx-proxy-manager/**'
  # logs
  - '+ /mnt/source/docker/grafana/**'
  - '+ /mnt/source/docker/loki/**'
  # taiga
  - '+ /mnt/source/docker/taiga/media/**'
  - '+ /mnt/source/docker/taiga/static/**'
  # borgmatic config
  - '+ /etc/borgmatic.d/*.yaml'
  # ignore rest
  - '- **'

repositories:
  - path: /mnt/backup/docker
    label: local

archive_name_format: 'docker-backup-{now:%Y-%m-%d-%H%M%S}'

after_backup:
  - echo Syncing backups
  - rclone sync /mnt/backup/docker bb:phoenix0/docker --progress --stats-one-line --stats 1s
  - rclone sync /mnt/backup/docker koofr:/docker --progress --stats-one-line --stats 1s
  - rclone sync /mnt/backup/docker gdrive:/docker --progress --stats-one-line --stats 1s
  - echo Finished backup sync

<<: !include /etc/borgmatic.d/shared/shared-config.yaml