- name: Create mariadb network bridge
  docker_network:
    name: "{{ mariadb_network }}"
    driver: bridge

- name: Create mariadb socket volume
  docker_volume:
    volume_name: "{{ mariadb_socket }}"

- name: Create / Run {{ container }} container
  docker_container:
    name: "{{ container }}"
    image: mariadb:latest
    networks:
      - name: "{{ mariadb_network }}"
      - name: "docker_macvlan"
        ipv4_address: "{{ (netplan_base, 25) | join('.') }}" # probably remove this
    pull: true
    state: started
    env:
      MARIADB_USER: "{{ mariadb_user }}"
      MARIADB_PASSWORD: "{{ mariadb_user_password }}"
      MARIADB_ROOT_PASSWORD: "{{ mariadb_root_password }}"
    ports:
      - "3306:3306"
    volumes:
      - "{{ docker_dir }}/{{ container }}:/{{ mariadb_script_directory }}"
      - "{{ mariadb_socket }}:/var/run/mysqld"
    restart_policy: unless-stopped

- name: Set target_container to {{ container }}
  set_fact:
    target_container: "{{ container }}"

- include_tasks: get_single_docker_container_ready.yml

- name: Create {{ container }} scripts directory
  community.docker.docker_container_exec:
    container: "{{ container }}"
    argv:
      - /bin/bash
      - "-c"
      - "mkdir {{ mariadb_script_directory }} > /dev/stderr"
    chdir: /root
  failed_when: 
    - result.stderr.find("File exists") == -1
    - result.rc != 0
  register: result