- name: Create mariadb socket volume
  docker_volume:
    volume_name: "{{ mariadb_socket }}"
- name: Create / Run {{ container }} container
  docker_container:
    name: "{{ container }}"
    image: mariadb:latest
    networks:
      - name: "docker_macvlan"
        ipv4_address: "{{ mariadb_address }}"
    pull: true
    state: started
    env:
      MARIADB_USER: "{{ mariadb_user }}"
      MARIADB_PASSWORD: "{{ mariadb_user_password }}"
      MARIADB_ROOT_PASSWORD: "{{ mariadb_root_password }}"
    ports:
      - "3306:3306"
    volumes:
      - "{{ mariadb_socket }}:/var/run/mysqld"
    restart_policy: unless-stopped

- name: Set target_container to {{ container }}
  set_fact:
    target_container: "{{ container }}"

- include_tasks: get_single_docker_container_ready.yml