---
- name: Install required system packages
  apt:
    name: mergerfs
    state: present
    update_cache: yes

- name: Mount the mergerfs array
  mount:
    name: "{{ mergerfs_root }}"
    src: /mnt/data-*
    opts: "cache.files=partial,dropcacheonclose=true,category.create=mfs,direct_io,defaults,allow_other,moveonenospc=1,minfreespace=10G,fsname=mergerfs,uid={{ sudo_user_uid }},gid={{ sudo_user_gid }}"
    fstype: fuse.mergerfs
    state: mounted
  when: data_disks[0] is defined