- name: Get lldap groups
  uri:
    url: http://{{ lldap_address }}:{{ lldap_ui_port }}/api/graphql
    method: POST
    status_code: 200
    headers: "{{ lldap_headers }}"
    body_format: json
    body:
      query: |
        {
          groups {
            id
            displayName
            users {
              id
            }
          }
        }
  register: result

- name: Get group {{ lldap_group.group }} information
  set_fact:
    lldap_group_info: "{{ result.json.data.groups | selectattr('displayName', 'defined') | selectattr('displayName', '==', lldap_group.group) | first }}"

- name: Add user {{ lldap_group.user }} to group {{ lldap_group.group }}
  uri:
    url: http://{{ lldap_address }}:{{ lldap_ui_port }}/api/graphql
    method: POST
    status_code: 200
    headers: "{{ lldap_headers }}"
    body_format: json
    body:
      operationName: addUserToGroup
      query: |
        mutation addUserToGroup($userId: String!, $groupId: Int!) {
          addUserToGroup(userId: $userId, groupId: $groupId) {
            ok
          }
        }
      variables:
        userId: "{{ lldap_group.user }}"
        groupId: "{{ lldap_group_info.id | int }}"
  when: lldap_group_info is defined and not (lldap_group.user in lldap_group_info.users)