- include_tasks: roles/containers/network/lldap/tasks/get_lldap_existing_users.yml
  when: lldap_users_existing is not defined

- name: Create user {{ lldap_user.id }}
  uri:
    url: https://{{ lldap_domain }}/api/graphql
    method: POST
    status_code: 200
    headers: "{{ lldap_headers }}"
    body_format: json
    body:
      operationName: CreateUser
      query: |
        mutation CreateUser($user: CreateUserInput!) {
          createUser(user: $user) {
            id
            creationDate
          }
        }
      variables:
        user: "{{ lldap_user }}"
  when: not (lldap_user.id in lldap_users_existing)

- name: Add user {{ lldap_user.id }} to existing users
  set_fact:
    lldap_users_existing: "{{ lldap_users_existing + [ lldap_user.id ] }}"
  when: not (lldap_user.id in lldap_users_existing)

- name: Create user ldif
  copy:
    content: |
      dn: {{ lldap_user_attribute }}={{ user.id }},{{ lldap_user_dn }}
      objectclass: inetOrgPerson
      objectclass: posixAccount
      objectclass: mailAccount
      objectclass: person
      uid: {{ user.id }}
      mail: {{ user.email }}
      cn: Administrator
    dest: "/tmp/account.ldif"

# sudo apt install ldap-utils
# ldapadd -H lldap://lldap:3890 -x -D "{{ lldap_user_attribute }}={{ lldap_admin_user }},{{ lldap_user_dn }}" -w "{{ lldap_admin_password }}" -f "/tmp/account.ldif"