- name: Create {{ container }} db user script
  copy:
    content: |
      CREATE USER IF NOT EXISTS {{ lldap_mysql_user }}@`{{ (mariadb_network.base, '%') | join('.') }}` IDENTIFIED BY '{{ lldap_mysql_password }}';
      GRANT USAGE, EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE  ON `{{ container }}_%`.* TO {{ lldap_mysql_user }}@`{{ (mariadb_network.base, '%') | join('.') }}`;
    dest: "{{ docker_dir }}/{{ mariadb_container }}/{{ container }}_user.sql"

- name: Execute {{ container }} db user script
  community.docker.docker_container_exec:
    container: "{{ mariadb_container }}"
    argv:
      - /bin/bash
      - "-c"
      - "mysql --user=root --password={{ mariadb_root_password }} < /{{ mariadb_script_directory }}/{{ container }}_user.sql"
    chdir: /root

- name: Remove {{ container }} db user script
  file:
    path: "{{ docker_dir }}/{{ mariadb_container }}/{{ container }}_user.sql"
    state: absent

- name: Create {{ container }} db
  community.docker.docker_container_exec:
    container: "{{ mariadb_container }}"
    argv:
      - /bin/bash
      - "-c"
      - "mysql --user=root --password={{ mariadb_root_password }} -e \"CREATE DATABASE IF NOT EXISTS {{ container }}_{{ database }}\""
    chdir: /root