- name: Create / Run {{ container }} container
  docker_container:
    name: "{{ container }}"
    image: nitnelave/lldap:latest
    networks:
      - name: "{{ mariadb_network.name }}"
      - name: "{{ swag_network.name }}"
    pull: true
    state: started
    env:
      UID: "{{ target_username_puid }}"
      GID: "{{ target_username_pgid }}"
      TZ: "{{ timezone }}"
      LLDAP_JWT_SECRET: "{{ lldap_jwt_secret }}"
      LLDAP_LDAP_USER_DN: "{{ lldap_ldap_user }}"
      LLDAP_LDAP_USER_PASS: "{{ lldap_ldap_password }}"
      LLDAP_LDAP_BASE_DN: "{{ ['dc='] | product(swag_domain | split('.')) | map('join') | join(',') }}"
      LLDAP_DATABASE_URL: "mysql://{{ lldap_mysql_user }}:{{ lldap_mysql_password }}@{{ mariadb_container }}/{{ container }}_{{ database }}"
    ports:
      - "3890:3890"
      - "17170:17170"
    volumes:
      - "{{ docker_dir }}/{{ container }}:/data"
    restart_policy: unless-stopped

- name: Restart {{ container }} containers
  docker_container:
    name: "{{ container }}"
    state: started
    restart: true