- name: Create / Run {{ container }} container
  docker_container:
    name: "{{ container }}"
    image: nitnelave/lldap:latest
    networks:
      - name: "docker_macvlan"
        ipv4_address: "{{ container_address }}" # probably remove this
    pull: true
    state: started
    env:
      UID: "{{ sudo_user_uid | string }}"
      GID: "{{ sudo_user_gid | string }}"
      TZ: "{{ timezone }}"
      LLDAP_JWT_SECRET: "{{ lldap_jwt_secret }}"
      LLDAP_LDAP_USER_DN: "{{ lldap_admin_user }}"
      LLDAP_LDAP_USER_PASS: "{{ lldap_admin_password }}"
      LLDAP_LDAP_BASE_DN: "{{ lldap_base_dn }}"
      LLDAP_DATABASE_URL: "mysql://{{ lldap_mysql_user }}:{{ lldap_mysql_password }}@{{ mariadb_address }}/{{ container }}_{{ database }}"
    ports:
      - "{{ lldap_ldap_port }}:{{ lldap_ldap_port }}"
      - "{{ lldap_ui_port }}:{{ lldap_ui_port }}"
    volumes:
      - "{{ docker_dir }}/{{ container }}/data:/data"
      - "{{ lldap_tools_dir }}:/tools"
    restart_policy: unless-stopped