- include_tasks: get_docker_container_defaults.yml

- name: Empty known {{ container }} container subdomains
  set_fact:
    swag_container_subdomains: []
  when: swag_container_subdomains is defined

- name: Get a list of containers using a {{ container }} subdomain
  delegate_to: localhost
  become: false
  set_fact:
    swag_container_subdomains: "{{ swag_container_subdomains | default([]) + [ item ] }}"
  with_items: "{{ container_defaults }}"
  when: item.swag_subdomain is defined

- name: Setup external CNAME records for containers with {{ container }} subdomains
  community.general.cloudflare_dns:
    zone: "{{ swag_cloudflare_zone }}"
    record: "{{ ([ item.swag_subdomain ] + swag_domain | regex_replace(swag_cloudflare_zone, '') | split('.')) | reject('match', '^$') | join('.') }}"
    type: CNAME
    value: "{{ ([ swag_cloudflare_cname_target ] + swag_cloudflare_zone | split('.')) | reject('match', '^$') | join('.') }}"
    proxied: true
    api_token: "{{ cloudflare_dns_token }}"
    state: present
  loop: "{{ swag_container_subdomains }}"