- include_tasks: get_docker_container_defaults.yml

- name: Empty known container subdomains
  set_fact:
    container_subdomains: []
  when: container_subdomains is defined

- name: Get a list of containers with subdomain & network
  delegate_to: localhost
  become: false
  set_fact:
    container_subdomains: "{{ container_subdomains | default([]) + [ item ] }}"
  with_items: "{{ container_defaults }}"
  when: item.subdomain is defined and item.network is defined

## move this to playbook start
- name: Get swag networks dictionary
  set_fact:
    swag_networks_dict: "{{ swag_networks_dict | default({}) | combine({ item['name']: value }) }}"
  loop: "{{ swag_networks }}"
  vars:
    keys: "{{ item.keys() | difference(['name']) }}"
    values: "{{ keys | map('extract', item) | list }}"
    value: "{{ dict(keys | zip(values)) }}"

- name: Setup external CNAME records for containers with subdomains
  community.general.cloudflare_dns:
    zone: "{{ swag_networks_dict[item.network].zone }}"
    record: "{{ ([ item.subdomain ] + swag_networks_dict[item.network].domain | regex_replace(swag_networks_dict[item.network].zone, '') | split('.')) | reject('match', '^$') | join('.') }}"
    type: CNAME
    value: "{{ swag_networks_dict[item.network].target | default(swag_networks_dict[item.network].domain) }}"
    proxied: true
    api_token: "{{ cloudflare_dns_token }}"
    state: present
  loop: "{{ container_subdomains }}"
  when: swag_networks_dict[item.network].internal is not defined or swag_networks_dict[item.network].internal == false