---

- name: Create / Run swag containers
  docker_container:
    name: "swag_{{ item.name }}"
    image: ghcr.io/linuxserver/swag
    pull: yes
    networks:
      - name: "docker_macvlan"
        ipv4_address: "{{ (netplan_base, item.container) | join('.') }}"
      - name: "swag_{{ item.name }}_bridge"
    capabilities:
      - net_admin
    state: started
    env:
      PUID: "{{ target_username_puid }}"
      PGID: "{{ target_username_pgid }}"
      TZ: "{{ timezone }}"
      URL: "{{ item.url }}"
      SUBDOMAINS: wildcard
      VALIDATION: dns
      DNSPLUGIN: cloudflare
      EMAIL: "{{ target_email }}"
    ports:
      - 443:443
    volumes:
      - "{{ docker_dir }}/swag/{{ item.name }}/nginx:/config/nginx"
      - "{% if 'local' in item %}{{ docker_dir }}/swag/{{ item.name }}/www:/config/www{% else %}omit{% endif %}"
      - "{{ docker_dir }}/swag/dns-conf:/config/dns-conf"
      - "{{ docker_dir }}/swag/letsencrypt:/config/etc/letsencrypt"
    restart_policy: unless-stopped
  loop: "{{ swag_networks }}"