---
- name: Create {{ container }} bridge network
  docker_network:
    name: "{{ swag_network.name }}"
    driver: bridge

- name: Create / Run {{ container }} container
  docker_container:
    name: "{{ container }}"
    image: ghcr.io/linuxserver/swag
    pull: yes
    networks:
      - name: docker_macvlan
        ipv4_address: "{{ (netplan_base, swag_network.address) | join('.') }}"
      - name: "{{ swag_network.name }}"
    capabilities:
      - net_admin
    state: started
    env:
      PUID: "{{ target_username_puid }}"
      PGID: "{{ target_username_pgid }}"
      TZ: "{{ timezone }}"
      URL: "{{ swag_domain }}"
      SUBDOMAINS: wildcard
      VALIDATION: dns
      DNSPLUGIN: cloudflare
      EMAIL: "{{ target_email }}"
    ports:
      - 443:443
    volumes:
      - "{{ docker_dir }}/{{ container }}/nginx:/config/nginx"
      - "{{ docker_dir }}/{{ container }}/dns-conf:/config/dns-conf"
      - "{{ docker_dir }}/{{ container }}/letsencrypt:/config/etc/letsencrypt"
    restart_policy: unless-stopped