---
- name: Create swag nginx proxy-configuration folder
  file:
    path: "{{ docker_dir }}/{{ container }}/nginx/proxy-confs/"
    state: directory
    recurse: yes
    mode: 0755

- include_tasks: get_docker_container_defaults.yml

- name: Get a list of all containers with swag_subdomain defined
  delegate_to: localhost
  become: false
  set_fact:
    swag_container_subdomains: "{{ swag_container_subdomains | default([]) + [ item ] }}"
  with_items: "{{ container_defaults }}"
  when: item.swag_subdomain is defined

- name: Get swag role directory
  delegate_to: localhost
  become: false
  find:
    paths: roles/containers
    patterns: "{{ container }}"
    file_type: directory
    recurse: yes
    depth: 3
  register: swag_role_dir

- name: Store reference to swag role templates directory
  set_fact:
    swag_template_dir: "{{ (swag_role_dir.files[0].path, 'templates') | path_join }}"

- name: Install swag_subdomain proxy configuration files
  template:
    src: "{{ (item.root, 'templates', 'subdomain.conf.j2') | path_join }}"
    dest: "{{ docker_dir }}/{{ container }}/nginx/proxy-confs/{{ item.container }}.subdomain.conf"
    mode: 0644
  with_items: "{{ swag_container_subdomains }}"
  notify:
    - restart swag
    - test nginx

- name: Create swag DNS configuration folder
  file:
    path: "{{ docker_dir }}/{{ container }}/dns-conf"
    state: directory
    recurse: yes
    mode: 0755

- name: Copy swag DNS configuration templates into DNS configuration folder
  template:
    src: "{{ item }}"
    dest: "{{ docker_dir }}/{{ container }}/dns-conf/{{ item | basename | regex_replace('.j2$', '') }}"
    mode: 0644
  with_fileglob:
    - templates/dns/*.ini.j2
  notify:
    - restart swag
