---

- include_tasks: install_configs.yml

- include_tasks: network_bridge.yml

- include_tasks: docker.yml

- include_tasks: cloudflare_real_ips.yml

- include_tasks: cloudflare_internal_dns.yml

- include_tasks: cloudflare_external_dns.yml