- name: Create macvlan networks
  docker_network:
    name: "swag_{{ item.name }}_macvlan"
    driver: macvlan
    driver_options:
      parent: "{{ (item.interface, net_idx + 1) | join('.') }}"
    ipam_config:
      - subnet: "{{ (swag_base, item.subnet) | join('.') }}"
        gateway: "{{ (swag_base, item.gateway) | join('.') }}"
  loop: "{{ swag_networks }}"
  loop_control:
    index_var: net_idx
  notify:
    - restart swag