services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.11.3
    container_name: nginx-proxy-manager
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - DISABLE_IPV6=true
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - $DATA_DIR/nginx-proxy-manager/data:/data
      - $DATA_DIR/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - $DATA_DIR/nginx-proxy-manager/snippets:/snippets
    healthcheck:
      test:
        - CMD
        - /usr/bin/check-health
      interval: 10s
      timeout: 3s
    restart: unless-stopped
  lldap:
    image: lldap/lldap:stable
    container_name: lldap
    environment:
      - UID=$PUID
      - GID=$PGID
      - TZ=$TZ
      - LLDAP_JWT_SECRET_FILE=/run/secrets/lldap_jwt_secret
      - LLDAP_LDAP_USER_DN_FILE=/run/secrets/lldap_ldap_user_dn
      - LLDAP_LDAP_BASE_DN_FILE=/run/secrets/lldap_ldap_base_dn
      - LLDAP_LDAP_USER_PASS_FILE=/run/secrets/lldap_ldap_user_pass
      - LLDAP_LDAP_USER_EMAIL=ro
      - LLDAP_DATABASE_URL_FILE=/run/secrets/lldap_database_url
    ports:
      - 10360:3890
      - 10361:17170
    volumes:
      - $DATA_DIR/lldap:/data
    secrets:
      - lldap_jwt_secret
      - lldap_ldap_user_dn
      - lldap_ldap_base_dn
      - lldap_ldap_user_pass
      - lldap_database_url
    restart: unless-stopped
  postgres:
    image: postgres:17.0
    container_name: postgres
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    ports:
      - 10364:5432
    volumes:
      - $DATA_DIR/postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d `cat $$POSTGRES_DB_FILE` -U `cat $$POSTGRES_USER_FILE`
      interval: 1s
      timeout: 5s
      retries: 10
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=$SMTP_USER
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_password
      - PGADMIN_CONFIG_LOGIN_BANNER="<h4>Authorised users only!</h4>"
    ports:
      - 10365:80
    volumes:
      - $DATA_DIR/pgadmin:/var/lib/pgadmin
    secrets:
      - pgadmin_password
    restart: unless-stopped
secrets:
  lldap_jwt_secret:
    file: $SECRET_DIR/LLDAP_JWT_SECRET
  lldap_ldap_user_dn:
    file: $SECRET_DIR/LLDAP_LDAP_USER_DN
  lldap_ldap_base_dn:
    file: $SECRET_DIR/LLDAP_LDAP_BASE_DN
  lldap_ldap_user_pass:
    file: $SECRET_DIR/LLDAP_LDAP_USER_PASS
  lldap_database_url:
    file: $SECRET_DIR/LLDAP_DATABASE_URL
  postgres_db:
    file: $SECRET_DIR/POSTGRES_DB
  postgres_user:
    file: $SECRET_DIR/POSTGRES_USER
  postgres_password:
    file: $SECRET_DIR/POSTGRES_PASSWORD
  pgadmin_password:
    file: $SECRET_DIR/PGADMIN_PASSWORD
networks: {}