---
collections:
  - name: community.general
  - name: community.docker
  - name: community.mysql
  - name: maxhoesel.pterodactyl
  
roles:
  - name: geerlingguy.security
  - name: geerlingguy.ntp
  - name: ironicbadger.snapraid