- hosts: source
  connection: local
  tasks:
    - name: Generate SSH Key
      openssh_keypair:
        path: "~/.ssh/{{ ssh_key_name }}" # Name of key
        state: present # Ensure key exists
        type: ed25519 # The algorithm used to generate the SSH private key
        force: False # Prevent key regen
        comment: "source:{{ hostvars['source']['ansible_host'] }}->target:{{ hostvars['target']['ansible_host'] }}" # public key metadata comment
    
    - name: Store the public key using Lookup
      set_fact:
        ssh_key: "{{ lookup('file', '~/.ssh/{{ ssh_key_name }}.pub') }}" # kvp, open public key, store in var

- hosts: target
  gather_facts: no
  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - port

- hosts: target
  become: yes
  # Init submodules
  roles:
    - role: system
      tags:
        - system
    
    - role: geerlingguy.security
      tags:
        - security

    - role: docker
      tags: 
        - docker
    
    - role: security/fail2ban
      tags:
        - fail2ban

    - role: filesystems/mounts
      tags:
        - mounts
    
    - role: filesystems/mergerfs
      tags:
        - mergerfs

    - role: filesystems/snapraid
      tags:
        - snapraid