- hosts: target
  gather_facts: false
  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - port

- hosts: target
  become: true
  # Init submodules
  roles:
    - role: system
      tags:
        - system
  
    - role: docker
      tags: 
        - docker

    - role: geerlingguy.security
      tags:
        - security

    - role: geerlingguy.ntp
      tags:
        - ntp

    - role: security/fail2ban
      tags:
        - fail2ban

    - role: security/iptables
      tags:
        - iptables

    - role: security/endlessh
      tags:
        - endlessh

    - role: filesystems/mounts
      tags:
        - mounts
    
    - role: filesystems/mergerfs
      tags:
        - mergerfs

    - role: filesystems/snapraid
      tags:
        - snapraid

    - role: containers/network/cloudflare-ddns
      tags:
        - container
        - cloudflare
        - ddns

    - role: containers/network/docker-socket-proxy
      tags:
        - container
        - docker-socket-proxy
        - docker-socket
        - socket-proxy
    
    - role: containers/network/swag
      tags:
        - container
        - swag

    - role: containers/services/vaultwarden
      tags:
        - container
        - swag
        - vaultwarden