- name: restart swag
  docker_container:
    name: "{{ item }}"
    state: started
    restart: yes
  when: container_state[item] is defined and container_state[item].Running == true
  with_items: "{{ container | split(',') }}"

- name: test nginx
  command:
    cmd: "docker exec -it {{ item }} /usr/sbin/nginx -c /config/nginx/nginx.conf -t"
  register: swag_nginx_test
  when: container_state[item] is defined and container_state[item].Running == true
  changed_when: swag_nginx_test is not search("test is successful")
  failed_when: swag_nginx_test is not search("test is successful")
  with_items: "{{ container | split(',') }}"

- name: ip route add
  become: yes
  command:
    cmd: ip route add {{ swag_network }} dev mynet-shim
