- name: restart swag
  docker_container:
    name: "{{ container }}"
    state: started
    restart: yes
  when: container_state[item] is defined and container_state[item].Running == true

- name: test nginx
  command:
    cmd: "docker exec -it {{ container }} /usr/sbin/nginx -c /config/nginx/nginx.conf -t"
  register: swag_nginx_test
  when: container_state[container] is defined and container_state[container].Running == true
  changed_when: swag_nginx_test is not search("test is successful")
  failed_when: swag_nginx_test is not search("test is successful")
  loop: "{{ container }}"