---

- include_tasks: get_docker_container_list.yml

- name: Empty known container info
  set_fact:
    container_info: {}
  when: container_info is defined

- name: Get list of container info
  docker_container_info:
    name: "{{ item }}"
  register: container_info
  loop: "{{ container_list.stdout_lines }}"