- include_tasks: get_docker_container_defaults.yml

- name: Empty known playbook container list
  set_fact:
    playbook_container_list: []
  when: playbook_container_list is defined

- name: Get a list of container names from defaults (str)
  delegate_to: localhost
  become: false
  set_fact:
    playbook_container_list: "{{ playbook_container_list | default([]) + [ item.container | string ] }}"
  when: item.container | type_debug != "list"
  with_items: "{{ container_defaults }}"

- name: Get a list of container names from defaults (list)
  delegate_to: localhost
  become: false
  set_fact:
    playbook_container_list: "{{ playbook_container_list | default([]) + item.container }}"
  when: item.container | type_debug == "list"
  with_items: "{{ container_defaults }}"