- name: Get container info
  docker_container_info:
    name: "{{ item }}"
  register: result

- name: Restart container
  docker_container:
    name: "{{ item }}"
    state: started
    restart: true
  when: result.exists