---

# - name: Determine current data drive filesystems
#   command: "/sbin/blkid -s TYPE -o value {{ item.dev }}"
#   register: disk_blkid
#   with_items: "{{ disks }}"

- name: Merge drive lists
  set_fact:
    all_disks: "{{ data_disks + parity_disks }}"

- name: Create data drive filesystems
  filesystem:
    fstype: xfs
    dev: "{{ item.dev }}"
    opts: "-L {{ item.label }}"
  with_items: "{{ all_disks }}"
  when: all_disks[0] is defined

- name: Mount the data drives
  mount:
    path: "/mnt/{{ item.label }}"
    src: "/dev/disk/by-label/{{ item.label }}"
    fstype: xfs
    state: mounted
    passno: "2"
  with_items: "{{ all_disks }}"
  when: all_disks[0] is defined