snapraid_bin_path: /usr/bin/snapraid
snapraid_runner_command: "python3 {{ snapraid_runner_bin }} -c {{ snapraid_runner_conf }}"

# 1. Stop all the docker containers
# 2. Backup the {{ docker_dir }} to the MergerFS pool
# 3. Start the containers back up
# 4. Execute the snapraid runner and 
# Stopping the containers is necessary – backing up the data folder with the containers running will result in corrputed database files and no files can be changed during the Snapraid sync
snapraid_runner_cron_jobs:
  - {
      job: "
        docker ps -q | xargs --no-run-if-empty docker stop;
        rsync -avz --delete --exclude cache {{ docker_dir }} {{ mergerfs_root }}/docker_data;
        docker ps -a -q | xargs --no-run-if-empty docker start;
      ",
      name: "snapraid_runner",
      weekday: "0",
      hour: "3",
    }

snapraid_runner_delete_threshold: -1
snapraid_runner_email_sendon: "error"

snapraid_content_files:
  - /var/snapraid.content

snapraid_config_excludes:
  - "*.unrecoverable"
  - "*.!sync"
  - /tmp/
  - "/download/*"

# don't touch
snapraid_runner_email_address: "{{ sender_email }}"
snapraid_runner_email_pass: "{{ sender_password }}"
snapraid_runner_email_address_from: "{{ sender_email }}"
snapraid_runner_email_address_to: "{{ target_email }}"
snapraid_runner_smtp_host: "{{ sender_smtp_host }}"
snapraid_runner_smtp_port: "{{ sender_smtp_port }}"
snapraid_runner_use_ssl: true