netplan_config:
  network:
    ethernets:
      eth0:
        dhcp4: false
        dhcp6: false
        addresses: 
          - 192.168.1.176/24
        routes:
          - to: default
            via: 192.168.1.254
        nameservers:
          addresses:
            - 192.168.1.254
            - 1.1.1.1
            - 1.1.0.0
    version: 2