# Sudoer
sudo_user: "{{ ansible_user }}"
sudo_user_gid: "{{ ansible_user_gid }}"
sudo_user_uid: "{{ ansible_user_id }}"

# Drive mounts
data_disks:
  - { dev: /dev/sda, label: data-0, content: true }
  - { dev: /dev/sdb, label: data-1, content: true }

parity_disks:
  - { dev: /dev/sdc, label: parity-0, content: true }

# MergerFS
mergerfs_root: /mnt/storage

# Docker
docker_dir: /opt/docker/data

# Timezone
timezone: Europe/London