- name: Create {{ container_root }} data directory
  file:
    path: "{{ docker_dir }}/{{ item.container }}"
    state: directory
  loop: "{{ containers }}"

- name: Install {{ container_root }} configuration
  template:
    src: configuration.yml.j2
    dest: "{{ docker_dir }}/{{ item.container }}/configuration.yml"
  loop: "{{ containers }}"

- name: Install {{ container_root }} swag nginx location conf
  template:
    src: authelia-location.conf.j2
    dest: "{{ docker_dir }}/swag/{{ item.network }}/nginx/authelia-location.conf"
  loop: "{{ containers }}"

- name: Install {{ container_root }} swag nginx server conf
  template:
    src: authelia-server.conf.j2
    dest: "{{ docker_dir }}/swag/{{ item.network }}/nginx/authelia-server.conf"
  loop: "{{ containers }}"

- name: Restart swag containers
  docker_container:
    name: "swag_{{ item.network }}"
    state: started
    restart: true
  loop: "{{ containers }}"