- name: Get all defined {{ container }} rule subjects
  set_fact:
    authelia_subjects: "{{ authelia_subjects | default([]) + item.authelia_rules | selectattr('subject', 'defined') | map(attribute='subject') }}"
  loop: "{{ container_authelia_rules }}"
  when: item.authelia_rules is defined and item.authelia_rules | selectattr('subject', 'defined') | length > 0

- name: Get all defined groups from {{ container }} rule subjects
  set_fact:
    authelia_groups: "{{ authelia_subjects | flatten | select('match', 'group:.*') | map('regex_replace', '(group:)', '') | unique }}"

- name: Create LLDAP groups
  include_tasks: roles/containers/network/lldap/tasks/add_lldap_group.yml
  loop: "{{ authelia_groups | unique }}"
  loop_control:
    loop_var: lldap_group
