- name: Create {{ container }} swag data directory
  file:
    path: "{{ docker_dir }}/swag/{{ network }}/nginx"
    state: directory

- name: Install {{ container }} swag nginx location conf
  template:
    src: authelia-location.conf.j2
    dest: "{{ docker_dir }}/swag/{{ network }}/nginx/authelia-location.conf"


- name: Install {{ container }} swag nginx server conf
  template:
    src: authelia-server.conf.j2
    dest: "{{ docker_dir }}/swag/{{ network }}/nginx/authelia-server.conf"

- name: Restart swag containers
  include_tasks: "restart_docker_container.yml"
  vars:
    target_container: swag_{{ network }}