macvlan_name: docker_macvlan
macvlan_interface: "dm_host_bridge"
macvlan_subnet: 0/24 # available: [ 0 - 255 ] usable: [ 1 - 253 ]
macvlan_gateway: "{{ netplan_gateway }}"
macvlan_range: 0/27 # available: [ 0 - 31 ] usable: [ 1 - 30 ]
macvlan_host: 29