---
- name: Remove cloud-config to avoid boot delay
  apt:
    name: cloud-config
    state: absent
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Make sure iSCSId and Open-iSCSId services are disabled
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - iscsid
    - open-iscsi