---
- include_tasks: passwordless.yml

- name: Suppress login messages
  file:
    name: /home/{{ sudo_user }}/.hushlogin
    mode: 0644
    state: touch
    owner: "{{ sudo_user }}"
    group: "{{ sudo_user }}"
    modification_time: preserve
    access_time: preserve

- include_tasks: boot_delay.yml

- name: Update and upgrade apt packages (Debian and Ubuntu)
  when: ansible_os_family == 'Debian'
  apt:
    upgrade: yes
    autoremove: yes
    update_cache: yes

- include_tasks: reboot.yml

- include_tasks: netplan.yml
  tags:
    - netplan
  when: netplan_config is defined

- name: Get public ip address
  community.general.ipify_facts:
  failed_when: ipify_public_ip is not defined