---
- include_tasks: passwordless.yml

- include_tasks: user.yml

- name: Suppress login messages
  file:
    name: /home/{{ target_username }}/.hushlogin
    mode: 0644
    state: touch
    owner: "{{ target_username }}"
    group: "{{ target_username }}"
    modification_time: preserve
    access_time: preserve

- include_tasks: boot_delay.yml

- name: Update and upgrade apt packages (Debian and Ubuntu)
  when: ansible_os_family == 'Debian'
  apt:
    upgrade: yes
    autoremove: yes
    update_cache: yes

- include_tasks: reboot.yml

- include_tasks: netplan.yml
  tags:
    - netplan
  when: netplan_config is defined