---
- include_tasks: "passwordless.yml" # The name of the imported file

- include_tasks: "ssh.yml" # The name of the imported file

- name: Suppress login messages
  file:
    name: /home/{{ target_username }}/.hushlogin
    mode: 0644
    state: touch
    owner: "{{ target_username }}"
    group: "{{ target_username }}"
    modification_time: preserve
    access_time: preserve