---
- name: Set the name of a sudo group
  set_fact:
    sudo_group: sudo

- name: Allow "sudo" group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%{{ sudo_group }}"
    line: "%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"