- name: Install python3 pkgs
  apt:
    pkg:
      - python3-pip
      - python3-setuptools
    state: latest
    update_cache: true

- name: pip install wheel 
  pip:
    name: wheel

- name: pip install PyMySQL for mysql module 
  pip:
    name: PyMySQL