---

- name: Get user {{ target_username }} puid
  getent:
    database: passwd
    key: "{{ target_username }}"
    fail_key: yes

- name: Get user {{ target_username }} pgid
  getent:
    database: group
    key: "{{ target_username }}"
    fail_key: yes

- name: Store user {{ target_username }} puid, pgid
  set_fact:
    target_username_puid: "{{ getent_passwd[target_username].1 }}"
    target_username_pgid: "{{ getent_group[target_username].1 }}"