---
container: sonarr
subdomain: sonarr
network: "{{ swag_network.public }}"

homepage_group: media
homepage_description: tv scraper

download_client_defaults:
  enable: true
  protocol: torrent
  priority: 1
  removeCompletedDownloads: true
  removeFailedDownloads: true
  fields:
    tvCategory: "tv-sonarr"
    recentTvPriority: 0
    olderTvPriority: 0
    addPaused: false

download_clients:
  - name: deluge
    fields:
      host: "{{ deluge_url }}"
      port: "{{ deluge_port }}"
      password: "{{ deluge_password }}"
    implementationName: Deluge
    implementation: Deluge
    configContract: DelugeSettings

