- name: disable ansible network
  set_fact:
    authelia_temporary_control: false

- name: reinstall authelia configuration
  template:
    src: configuration.yml.j2
    dest: "{{ docker_dir }}/{{ container }}/configuration.yml"
  listen: "disable ansible network"

- name: restart authelia container
  docker_container:
    name: "{{ container }}"
    state: started
    restart: true
  listen: "disable ansible network"