- name: Create {{ container }} authentication headers
  set_fact:
    jellyfin_headers: 
      X-Emby-Authorization: 'MediaBrowser Client="ansible", Device="ansible", DeviceId="ansible", Version="0.0.1"'

- name: Authenticate to {{ container }}
  uri:
    url: "https://{{ jellyfin_domain }}/Users/AuthenticateByName"
    method: POST
    status_code: 200
    headers: "{{ jellyfin_headers }}"
    body_format: json
    body: 
      Username: admin
      Pw: admin
  register: result

- name: Add token to {{ container }} authentication headers
  set_fact:
    jellyfin_user_id: "{{ result.json.User.Id }}"
    jellyfin_headers: "{{ jellyfin_headers | combine({ 'X-Mediabrowser-Token': result.json.AccessToken }) }}"