---
- include_tasks: repo_arch.yml

- name: Include OS-specific variables
  include_vars: "{{ ansible_facts['distribution'] | lower }}.yml"

- name: Install required system packages
  package:
    state: present
    name: "{{ docker_deps }}"

- name: Install Docker (Ubuntu)
  include_tasks: ubuntu.yml
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install Docker (Raspbian)
  include_tasks: raspbian.yml
  when: ansible_facts["distribution"] == "Debian"

- name: Update apt and install docker-ce
  when: ansible_facts["os_family"] == "Debian"
  apt:
    update_cache: yes
    name: "{{ docker_packages }}"
    state: present

- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: Add user "{{ target_username }}" to group docker
  user:
    name: "{{ target_username }}"
    groups:
      - docker
    append: yes

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Make sure Docker is running and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Cleanup inactive / removed containers
  include_tasks: cleanup.yml

- name: Create / Restore data directory
  include_tasks: data_directory.yml
