- include_tasks: repo_arch.yml

- name: Include os-specific variables
  include_vars: "{{ os_distro }}.yml"

- name: Install required system packages
  package:
    state: present
    name: "{{ docker_deps }}"

- name: Install docker (Default)
  when: os_distro != "raspbian"
  block:
  - name: Get docker GPG apt key
    apt_key:
      url: https://download.docker.com/linux/{{ os_distro }}/gpg
      state: present

  - name: Add docker repository
    apt_repository:
      repo: deb [arch={{ repo_arch }}] https://download.docker.com/linux/{{ os_distro }} {{ ansible_lsb["codename"] }} stable
      state: present

- name: Update apt and install docker-ce
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes

