- include_tasks: repo_arch.yml

- name: Include os-specific variables
  include_vars: "{{ os_distro }}.yml"

- name: Install required system packages
  package:
    state: present
    name: "{{ docker_deps }}"