---
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/raspbian/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: "deb [arch=arm64] https://download.docker.com/linux/raspbian bullseye stable"
      state: present

  - name: Switch to iptables-legacy
    alternatives:
      name: iptables
      path: /usr/sbin/iptables-legacy

  - name: Switch to ip6tables-legacy
    alternatives:
      name: ip6tables
      path: /usr/sbin/ip6tables-legacy

  - name: Switch to pip3
    alternatives:
      name: pip
      link: /usr/bin/pip
      path: /usr/bin/pip3

  - name: Switch to python3
    alternatives:
      name: python
      link: /usr/bin/python
      path: /usr/bin/python3