---
- include_tasks: get_docker_container_defaults.yml

- name: Retrieve list of services groups
  set_fact:
    service_groups: "{{ container_defaults | selectattr('homepage_group', 'defined') | map(attribute='homepage_group') | map('lower') | unique }}"

- name: Create homepage config directories
  file:
    path: "{{ docker_dir }}/{{ container }}"
    state: directory

- name: Install homepage services layout
  template:
    src: "services.yaml.j2"
    dest: "{{ docker_dir }}/{{ container }}/services.yaml"
    mode: 0644

- name: Install homepage docker config
  template:
    src: "docker.yaml.j2"
    dest: "{{ docker_dir }}/{{ container }}/docker.yaml"
    mode: 0644

- name: Install homepage widgets config
  template:
    src: "widgets.yaml.j2"
    dest: "{{ docker_dir }}/{{ container }}/widgets.yaml"
    mode: 0644

- name: Install homepage bookmarks config
  template:
    src: "bookmarks.yaml.j2"
    dest: "{{ docker_dir }}/{{ container }}/bookmarks.yaml"
    mode: 0644

- name: Create / Run homepage containers
  docker_container:
    name: "{{ container }}"
    image: ghcr.io/benphelps/homepage:latest
    networks:
      - name: "{{ swag_network.name }}"
    pull: true
    state: started
    env:
      PUID: "{{ target_username_puid }}"
      PGID: "{{ target_username_pgid }}"
    volumes:
      - "{{ docker_dir }}/{{ container }}:/app/config"
      - "{{ mergerfs_root }}:{{ mergerfs_root }}"
    restart_policy: unless-stopped
